Chunked reading
cta-observatory/pycorsikaio pull request #29
Opened 2023-03-27 19:44 UTC by maxnoe

2023-03-28 14:07 UTC, HealthyPear commented
I tested this on my 135 Gb file and I to read the first e.g. 10 events I get

97.831 s for the main branch
81.578 s for this branch

with `parse_blocks=True` I get an improvement of

3 s in main
~11 s in this branch

2023-03-28 15:09 UTC, maxnoe commented
> with parse_blocks=True I get an improvement of
> 
> 3 s in main
> ~11 s in this branch

Wait: did you switch the numbers here or is it actually worse on this branch?

2023-03-28 15:14 UTC, maxnoe commented
I am not sure I follow, so you ran multiple tests? Could you state explicitly the matrix of branch name and parse_blocks = {True, False}?

2023-03-28 15:20 UTC, HealthyPear commented
> I am not sure I follow, so you ran multiple tests? Could you state explicitly the matrix of branch name and parse_blocks = {True, False}?

| branch  | `parse_blocks = True`  | `parse_blocks = False` |
| ------------- | ------------- | ------------- |
| main  | ~95 s  | ~98 s  |
| this  | ~70s s  | ~81 s  |

2023-03-28 15:27 UTC, HealthyPear requested changes
Not sure, but maybe an additional test is needed where you read the 1 big chunk and you check that you reach the expected block?

2023-03-28 15:33 UTC, maxnoe commented on corsikaio/io.py
> +    is_fortran_file = True
Changed to a module constant.

2023-03-28 15:33 UTC, maxnoe commented on corsikaio/file.py
> +            # block = next(self._block_iter)
removed

2023-03-28 15:54 UTC, HealthyPear commented
> Edit: I am _very_ confused that your code takes longer with prase_blocks=False, it should be the other way around (and quite dramatically so).

mmm I don't know what happened but now if I try to use True I get a crash,

```
File "/home/CTA/peresano/pycorsikaio/../test_pycorsikaio_simplest.py", line 10, in <module>
    if event.header['event_number']==11:
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

2023-03-28 16:31 UTC, maxnoe commented
> mmm I don't know what happened but now if I try to use False I get a crash,

That's to be expected. The effect of `parse_blocks=False` is that the data in the blocks is not parsed, you get the raw array of 273 floats.

2023-03-29 11:55 UTC, HealthyPear commented
> > mmm I don't know what happened but now if I try to use False I get a crash,
> 
> That's to be expected. The effect of `parse_blocks=False` is that the data in the blocks is not parsed, you get the raw array of 273 floats.

Then please ignore the table above, I don't know what happened, maybe I edited the script without saving it or something like that...

Best if we deal with time profiling separately, this PR is healthy enough for its scope.

2023-03-29 12:04 UTC, merged